"""initial migration

Revision ID: 91f445b1a7ed
Revises: 
Create Date: 2026-09-24 19:30:56.382593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f445b1a7ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'internal_note',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task', 'internal_note',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
